### ISSUE TITLE
3.2.2 stemming "oed" crashes

### ISSUE THREAD

**Issue by andrian7** [nltk/nltk#1600]
```
from nltk.stem.porter import *
stemmer = PorterStemmer()
stemmer.stem("oed")
```

--> crash

The problem is a vowel suffixed by "ed" or "ing". It works in 3.2.1

python version: 3.5.2

**Comment by nschneid** [comment]
Works for me (NLTK 3.2.2 on Python 3.5.2):

```py
>>> from nltk.stem.porter import *
>>> stemmer = PorterStemmer()
>>> stemmer.stem("doing")
'do'
```

Also works for me on Python 2.7.3. Could this have something to do with nltk_data installations?

**Comment by andrian7** [comment]
@nschneid  Sorry, please try "oed" instead of "doing" 

(fixed it in the original post)

**Comment by nschneid** [comment]
See #1582.

**Comment by andrian7** [comment]
ah ok then closed

**Comment by borisnadion** [comment]
stemmer.stem("oing") still fails on 3.2.2 and https://github.com/nltk/nltk/pull/1582/files#diff-3a8479d9e81a5bd798ce0a2cd1b6dd9cR214 will not fix it, what do i miss?
