### ISSUE TITLE
NLTK depends on corenlp, should not be optional sub dependency

### ISSUE THREAD

**Issue by pykler** [nltk/nltk#1725]
Here is the exception with NLTK 3.2.3

```
.pyenv/lib/python2.7/site-packages/nltk/__init__.py:128: in <module>
    from nltk.chunk import *
.pyenv/lib/python2.7/site-packages/nltk/chunk/__init__.py:157: in <module>
    from nltk.chunk.api import ChunkParserI
.pyenv/lib/python2.7/site-packages/nltk/chunk/api.py:13: in <module>
    from nltk.parse import ParserI
.pyenv/lib/python2.7/site-packages/nltk/parse/__init__.py:81: in <module>
    from nltk.parse.corenlp import CoreNLPParser, CoreNLPDependencyParser
.pyenv/lib/python2.7/site-packages/nltk/parse/corenlp.py:17: in <module>
    import requests
E   ImportError: No module named requests
```

**Comment by alvations** [comment]
To use the `corenlp` module, install with

```
pip install -U nltk[corenlp]
```

And for fuzz-free installation:

```
pip install -U nltk[all]
```

Sorry about the lack of documentation for `corenlp` api, @dimazest will be preparing it in the coming days.  I think the documentation for the optional `corenlp` installation would be documented by then too.

**Comment by pykler** [comment]
@alvations all i did was import nltk, and it crashed. Are you not supposed to install nltk without any optional dependencies?

**Comment by alvations** [comment]
Ah I see. Yes then adding `requests` would be necessary because of it was exposed at https://github.com/nltk/nltk/blob/develop/nltk/parse/__init__.py#L81 

I think commenting out the import there would be more appropriate than adding additional dependencies that only one module uses.

**Comment by stevenbird** [comment]
I think this is resolved.

**Comment by stevenbird** [comment]
Can anyone replicate this problem?

**Comment by alvations** [comment]
@stevenbird The `requests` package needs to be installed if `corenlp` is to be used. 

#1725 will make the `requests` optional but users have to install with `pip install -U nltk[corenlp]` but that's on the develop branch.

Could the master branch be repackaged and an update on PyPI be made? `pip install nltk` from the current tarball on PyPI still throws the error:

```
alvas@ubi:~$ mkvirtualenv testnltk
Using base prefix '/usr'
New python executable in /home/alvas/.virtualenvs/testnltk/bin/python3
Also creating executable in /home/alvas/.virtualenvs/testnltk/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /home/alvas/.virtualenvs/testnltk/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/alvas/.virtualenvs/testnltk/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/alvas/.virtualenvs/testnltk/bin/preactivate
virtualenvwrapper.user_scripts creating /home/alvas/.virtualenvs/testnltk/bin/postactivate
virtualenvwrapper.user_scripts creating /home/alvas/.virtualenvs/testnltk/bin/get_env_details
(testnltk) alvas@ubi:~$ pip install nltk
Collecting nltk
Requirement already satisfied: six in ./.virtualenvs/testnltk/lib/python3.5/site-packages (from nltk)
Installing collected packages: nltk
Successfully installed nltk-3.2.3
(testnltk) alvas@ubi:~$ python
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alvas/.virtualenvs/testnltk/lib/python3.5/site-packages/nltk/__init__.py", line 128, in <module>
    from nltk.chunk import *
  File "/home/alvas/.virtualenvs/testnltk/lib/python3.5/site-packages/nltk/chunk/__init__.py", line 157, in <module>
    from nltk.chunk.api import ChunkParserI
  File "/home/alvas/.virtualenvs/testnltk/lib/python3.5/site-packages/nltk/chunk/api.py", line 13, in <module>
    from nltk.parse import ParserI
  File "/home/alvas/.virtualenvs/testnltk/lib/python3.5/site-packages/nltk/parse/__init__.py", line 81, in <module>
    from nltk.parse.corenlp import CoreNLPParser, CoreNLPDependencyParser
  File "/home/alvas/.virtualenvs/testnltk/lib/python3.5/site-packages/nltk/parse/corenlp.py", line 17, in <module>
    import requests
ImportError: No module named 'requests'
```

Maybe a v3.2.3a ?

**Comment by pykler** [comment]
What made me find this error, is we just had nltk as a dependency and suddenly all our imports broke. We do not use any optional packages, and furthermore I do believe that installing nltk, should allow nltk to be imported. Removing the import to corenlp from `nltk/__init__.py` or making it a required dependency seems fair, but currently its broken.

**Comment by stevenbird** [comment]
Resolved in version 3.2.4
